### PR TITLE
version 2.5.0-1.0: adapt upstream changes

### PR DESCRIPTION
**Pull request by jinzhongjia**
The adaptation of the build system has been completed temporarily, but because the upstream build.zig is damaged, ci cannot completely pass

### CODE REVIEW

**Comment by ttytm** [comment]
> The adaptation of the build system has been completed temporarily, but because the upstream build.zig is damaged, ci cannot completely pass

The compilation not working is unrelated to any upstream damage.
There's just a breaking change in Zig 13 regarding LazyPath and for zig-webui to support the Zig development version (which it probably wants to do, since this is all about Zig :D), it has to adapt to the changes / create a condition for it.

**Comment by jinzhongjia** [comment]
No, no, this is exactly related to the upstream. The zig build process is that if the dependent build.zig exists, then it will first build the dependent build.zig, and then return to the current project to build build.zig.

**Comment by jinzhongjia** [comment]
I will initiate a repair PR right away

**Comment by ttytm** [comment]
You can go ahead any, you'll see you will have to adapt the LazyPath usages and that it is the reason why it's not compiling with zig nightly. 
I've actually re-written the build-files of zig-webui. I would rather prefer to submit a PR here,  but didn't want to impose myself...

**Comment by jinzhongjia** [comment]
My original idea was to only retain the 0.11 adaptation in webui (for compatibility), not use 0.12 and later zig versions to build on the webui repository, and completely transfer these work to zig-webui, which will reduce the work quantity

**Comment by jinzhongjia** [comment]
But now that you have re-added 0.12 support, in order to ensure that nightly can be built successfully, I have to submit PR to the upstream again.

**Comment by jinzhongjia** [comment]
Zig is still a relatively niche language. I believe most users will still choose gcc or msvc when compiling webui.

**Pull request merged**
