### PR TITLE
feat: add new APIs and example

### PR DESCRIPTION
**Pull request by sensiblearts**
This PR surfaces `webui.get_free_port()`, from the latest build.

And to test it, a new `example` called, `custom_spa_server_on_free_port`.

Why this example?

I'm doing something like this with SvelteKit, so I built an example to test the approach. Use it or not, or alter it as you see fit.

Question: Is there something about my example that is causing click and navigation events to be dropped? 

(This example does not need those events -- only EVENT_CONNECTED and EVENT_DISCONNECTED, which are working fine -- but I need to figure out whether it's my code or an API change or a break.)

Thanks.

### CODE REVIEW

**Comment by jinzhongjia** [comment]
Okay, good PR, but there are some problems with the code. Can you let me modify it directly on your PR?

**Comment by sensiblearts** [comment]
p.s., I'll have to update this after your comments; does that mean that I should have created this as a "draft" PR?

**Comment by jinzhongjia** [comment]
I will update all the latest newly added APIs soon
No need to convert to draft

**Comment by sensiblearts** [comment]
Your comment appeared after I submitted mine. Lol.

Sure. How do I give you permission?

**Comment by jinzhongjia** [comment]
Haha, actually you gave me permission

**Comment by jinzhongjia** [comment]
pic

**Comment by sensiblearts** [comment]
Any time I submit a PR, just tell me what changes you want and I'll take care of it.

I can do more after work tomorrow.

Thanks.

**Comment by sensiblearts** [comment]
Also, if it's easy to a build step to copy all example .exe and supporting files (e.g., html) into their own subfolder -- it would be a good pattern across all `webui` platform builds, I think.

**Comment by jinzhongjia** [comment]
I think I should have fixed it, just use `zig build run_custom_spa_server_on_free_port`, it will work

But I'm not sure whether the running effect is what you need. You still need to confirm it.

**Comment by sensiblearts** [comment]
Thank you. I guess I didn't need to write all that copy files code! I'm learning.

I'll keep future PRs clean of that kind of stuff, or mark them as drafts.

**Comment by jinzhongjia** [comment]
Add APIs:
- `webui_get_free_port`
- `getPort`
- `getMimeType`

**Comment by sensiblearts** [comment]
I have to get to sleep; I'll check back tomorrow.

**Review by jinzhongjia — APPROVED** [review]

**Comment by sensiblearts** [comment]
@jinzhongjia would you like me to work on the spa/free_port example above? Just let me know if you want me to do anything. I don't want to spend time on it if you're doing it. Thanks.

**Comment by jinzhongjia** [comment]
so, you think this pr now is ok?
Then we can merge it

**Comment by sensiblearts** [comment]
Do you mean the whole PR (surfacing getFreePort, the stuff you added, my example app)? Or just the new API stuff.

Can you selectively merge, or is it all-or-nothing?

I'm not familiar with git workflow when 2 people have worked on a single pull request.

Before it's merged, I need to remove that copy file junk that I put in `build.zig`; how can I do that without overwriting what you've done?

Sorry I don't know more git. I've worked alone most of the time.

**Comment by jinzhongjia** [comment]
When two people handle a pull request, it can be regarded as two people using a branch together. You only need to pull regularly. You only need to delete and then push.

**Comment by sensiblearts** [comment]
Ok. I'll pull to get your edits. Then I'll clean up my stuff. Then push.

**Comment by sensiblearts** [comment]
I removed my commented-out code in `build.zig`. So you can merge if you feel it's ready.

However, there may still be a problem that will show up again. It's not a problem with this PR, I don't think.

The problem:

Yesterday, @hassandraga fixed the [missing events not being delivered to the handler (click, navigation)](https://github.com/webui-dev/webui/commit/fc0c867f25b0aa052c7dd26ac08a26e3079040d8) , which caused navigation to trigger a disconnect, [which he then fixed](https://github.com/webui-dev/webui/commit/fc0c867f25b0aa052c7dd26ac08a26e3079040d8). I pulled his changes, and at first it did not seemed fixed; so I cleaned zig-cache and zig-out and tried again, and still not fixed. Then I came back an hour later and ran it and it was fixed. And my own app (a SvelteKit SPA) is working fine like that.

Now, navigation seems to be again causing disconnect. E.g., in `custom_web_server` example, navigation to `second.html` disconnects and does not reconnect (to `second.html`'s `webui.js`).

Anyway, try to run the `custom_web_server` example and see what you think.

Problems that come and go, in a multi-threaded system, make me worry. But I could not be paying attention closely enough to what I'm doing.

**Comment by sensiblearts** [comment]
I can't work on it tomorrow, but Saturday I'll try to debug it. First, I'll see if it happens with other wrappers. Then I'll build webui in debug mode and see what I can figure out. I'd like to gain a deeper understanding of webui's internals, anyway.

**Comment by jinzhongjia** [comment]
I update zig-webui to the latest webui
is this ok? 
image

**Comment by sensiblearts** [comment]
@jinzhongjia it looks fixed. I think you can merge and then I'll pull and see if the problem is gone on my machine.

**Comment by sensiblearts** [comment]
@jinzhongjia @hassandraga I just pulled this newly merged PR, just after the `c_allocator` commit. Results:

- on WSL Ubuntu 20 (same machine), does NOT cause Disconnect, works fine.
- on Windows 10, still causes Disconnect and crash on Navigate link. My machine:

image

I'll dig into it tomorrow.

**Comment by jinzhongjia** [comment]
aha,I do not have machine with windows,maybe I can not help more 😞

**Comment by jinzhongjia** [comment]
em...
I will try fix it tomorrow

**Comment by sensiblearts** [comment]
This causes disconnect and crash, too, suggesting that it's the `navigate` call:

```
 switch (e.event_type) {
        .EVENT_CONNECTED => {
            std.debug.print("Connected. \n", .{});
        },
        .EVENT_DISCONNECTED => {
            std.debug.print("Disconnected. \n", .{});
        },
        .EVENT_MOUSE_CLICK => {
            std.debug.print("Click. \n", .{});
        },
        .EVENT_NAVIGATION => {
            const win = e.getWindow();
            win.navigate("http://localhost:8080/second.html");
        },
        else => {},
    }
```

@hassandraga forgive my memory, but after I run `mingw32-make debug` to generate the `webui` debug DLL, what else do I have to do to get `zig-webui` project to link it? I got it working once before but I forget what I did. I feel like I copied it to another folder...?

**Comment by sensiblearts** [comment]
(Interesting: I've not spent much time on the C examples, but when I did, I've been running the command `zig build examples` and then copying the resulting .exe into the example folder. E.g., `zig build examples` results in a `custom_web_server.exe` that I can copy into that example's folder and run. I won't do that anymore!)

Anyway, here are the C `make` results for `custom_web_server` example on Windows 10:

`mingw32-make debug`:
- `main.exe` runs fine: when you navigate, it disconnects but then instantly reconnects to the other page's `webui.js`
- Also, I scanned the debug logs and saw no hint of any error or crash
- Inspecting the browser console shows what you would expect, 200

`mingw32-make`:
- When `main.exe` is run, it looks ok until I click the nav link. When I do that
   - browser console: WebUI -> CMD -> Navigation [http://localhost:8080/second.html]                webui.js: 2
   - nothing happens -- it does not go to second.html
   - (I suspect that it has disconnected and wait() has returned.)
 - So I click the same link (on page index.html) a second time, and it _does_ go to `second.html`, but it is not connected:
 
second html
And I click to navigate back to `index.html` and I get a similar result:
index html

**Comment by sensiblearts** [comment]
Ok,thanks.

Is there a way to printf in release mode?

What if webui had a C `console.log` method, that made a JS call?

**Comment by jinzhongjia** [comment]
the new commit of webui seems fix this problem

**Comment by sensiblearts** [comment]
@jinzhongjia do you mean it's fixed on Windows?

**Comment by jinzhongjia** [comment]
> @jinzhongjia do you mean it's fixed on Windows?
I didn't test with windows, but I found that `custom_web_server` will also experience disconnection behavior under linux. But now it works fine

**Pull request merged**
